seed : 0

algo_params : 
  exploration : 0.1
  gamma : 0.99
  skip_steps : 4

update_cfg : 
  learning_rate : 0.001
  learning_rate_annealing : false
  max_grad_norm : 10
  max_buffer_size : -1
  batch_size : 64
  shared_encoder : false

train_cfg : 
  n_env_steps: 20000
  save_frequency: 10000
  