seed : 0

algo_params : 
  gamma : 0.99
  _lambda : 0.95
  clip_eps : 0.2
  entropy_coef: 0.01
  value_coef : 0.5
  normalize : true

update_cfg : 
  learning_rate : 0.0003
  learning_rate_annealing : true
  max_grad_norm : 0.5
  max_buffer_size : 128
  batch_size : 256
  n_epochs : 1
  shared_encoder : true

train_cfg : 
  n_env_steps : 500_000
  save_frequency : -1